version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    networks:
      - mern-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4192:4192"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/your_database
      - NODE_ENV=production
    depends_on:
      - mongodb
    networks:
      - mern-network

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "5174:80"
    networks:
      - mern-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge

volumes:
  mongodb_data: